spring:
  datasource:
    url: jdbc:postgresql://26.175.81.229:5432/inContact
    username: postgres
    password: root

  jpa:
    show-sql: true
    generate-ddl: true

access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}

refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}

server:
  port: 8000

